### ISSUE TITLE
week0 README mangled?

### ISSUE THREAD

**Issue by syndbg** [HackBulgaria/NodeJS-1#3]
The [week0 README](https://github.com/HackBulgaria/NodeJS-1/blob/master/week0/README.md) is exactly the same as [week8's README](https://github.com/HackBulgaria/NodeJS-1/blob/master/week8/README.md).

That might be unintentional in 476842f17570bd97673d89f7c35b1cb4d2fed475

**Comment by RadoRado** [comment]
Good catch :beer:
